version: 2.1

jobs:
  type-checking:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Install the packages"
          command: "npm install"
      - run:
          name: "Validate the types"
          command: "npm run tsc"
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Install the packages"
          command: "npm install"
      - run:
          name: "Run the tests"
          command: "npm run test"
workflows:
  main-workflow:
    jobs:
      - type-checking
      - test
